--- #YAML:1.0
name:               Bio-Trace-ABIF
version:            1.03
abstract:           Perl extension for reading and parsing ABIF (Applied
author:
    - Nicola Vitacolonna <vitacolonna@appliedgenomics.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
